config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  post "users/:id" => "users#show"
  get "home/about" => "homes#about"
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]

  resources :users, only: [:show, :edit, :update, :index, :create, :destroy]

end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book.id), notice: "You have created book successfully."
    else
      @books = Book.all
      @user = current_user
      render :'books/index'
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.new
    @books = Book.find(params[:id])
    @user = @books.user
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user == current_user
    else
      redirect_to books_path
    end

  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book.id), notice: "You have updated book successfully."
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path, notice: "Book was successfully destroyed"
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_list.html.erb
<h2>User info</h2>
      <%= attachment_image_tag user, :profile_image, :fill, 100, 100, format:'jpeg', fallback: "no_image-.jpeg" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= user.introduction %></th>
          </tr>
        </tbody>
      </table>
      <div class="row">
        <%= link_to "",edit_user_path(user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
      </div>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h1>Editing Book</h1>
        <% if @book.errors.any? %>
          <div id= "error_explanation">
            <h3><%= @book.errors.count %>error prohibited this book from being saved:</h3>
            <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>


      <%= form_with model:@book,local:true do |f| %>
        <div class="form-group">
          <label for="book_Title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book-opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
        <%= f.submit "Update Book", class: "btn btn-success" %>
        </div>
      <% end %>
      <%= link_to "Show", book_path(@book.id) %>
      |
      <%= link_to "Back", books_path %>
    </div>
  </div>
</div>

app/views/books/index.html.erb
<div class="container px-5 px-sm-0">
  <% if @book.errors.any? %>
    <div id= "error_explanation">
      <h3><%= @book.errors.count %> errors prohibited this object from being saved:</h3>
      <ul>
      <% @book.errors.full_messages.each do |message| %>
       <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format:'jpeg', fallback: "no_image-.jpeg" %>
      <table class="table">
        <tbody>
          <tr>
            <th>name</th>
            <th><%= @user.name %></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <%= link_to "", edit_user_path(@user.id), class: "btn btn-outline-secondary btn-block fas fa-user-cog" %>
      </div>

      <h2 class="mt-3">New book</h2>

      <%= form_with model: @book,local:true do |f| %>
        <div class="form-group">
          <label for="book_title">Title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>
        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>
        <div class="form-group">
        <%= f.submit "Create Book", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
         </thead>
        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user.id) do %>
              <%= attachment_image_tag book.user, :profile_image, :fill,40,40, format:'jpeg', fallback: "no_image.jpg", size: '40x40' %>
              <% end %>
            </td>
            <td><%= link_to book.title, book_path(book.id) %></td>
            <td><%= book.body %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>New book</h1>
<%= form_with model:@book,local:true do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>
  <h4>Opinion</h4>
  <%= f.text_area :body %>
  <%= f.submit "Create Book" %>
<% end %>

app/views/books/show.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render 'books/list', user: @user %>

      <h2 class="mt-3">New book</h2>
      <%= form_with model: @book,local:true do |f| %>
        <% if @book.errors.any? %>
        <div id= "error_explanation">
          <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
          <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
        <% end %>

    　　<div class="form-group">
          <label for="book_title">title</label>
          <%= f.text_field :title, class: "form-control book_title" %>
        </div>

        <div class="form-group">
          <label for="book_opinion">Opinion</label>
          <%= f.text_area :body, class: "form-control book_body" %>
        </div>

        <div class="form-group">
        <%= f.submit "Create Book", class: "btn btn-success" %>
        </div>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td>
              <%= link_to user_path(@user.id) do %>
                <%= attachment_image_tag @books.user, :profile_image, :fill, 40, 40, format:'jpeg', fallback: "no_image.jpg", size: '40x40' %><br>
                <%= @books.user.name %>
              <% end %>
            </td>
            <td><%= link_to @books.title, book_path(@books.user.id) %></td>
            <td><%= @books.body %></td>
            <% if @books.user.id == current_user.id %>
            <td><%= link_to "Edit", edit_book_path(@books.id), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@books.id), class: "btn btn-sm btn-danger", method: :delete,"data-confirm" => "本当に消しますか?" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>